### ISSUE TITLE
{ Bug + Update } plz update

### ISSUE THREAD

**Issue by lolminerxmrig** [jm33-m0/mec#47]
Hi
plz update

![image](https://user-images.githubusercontent.com/108659226/196060217-b1d51078-e008-4799-bcba-6c571ad2db72.png)

**Comment by jm33-m0** [comment]
From your screenshot it seems like your `PATH` is fucked up, and the installer script works fine in my tests. I see nothing to update.

**Comment by lolminerxmrig** [comment]
zoomeye api.
